package git

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/google/go-github/v57/github"
	"github.com/tapiaw38/tracehub-server/pkg/models"
)

// GitHubClient handles GitHub API operations
type GitHubClient struct {
	client *github.Client
	owner  string
	repo   string
}

// NewGitHubClient creates a new GitHub client
func NewGitHubClient(owner, repo string) *GitHubClient {
	// Get GitHub token from environment
	token := os.Getenv("GITHUB_TOKEN")
	if token == "" {
		token = os.Getenv("GH_TOKEN")
	}

	var client *github.Client
	if token != "" {
		client = github.NewClient(nil).WithAuthToken(token)
	} else {
		client = github.NewClient(nil)
	}

	return &GitHubClient{
		client: client,
		owner:  owner,
		repo:   repo,
	}
}

// CreatePullRequest creates a pull request on GitHub
func (gc *GitHubClient) CreatePullRequest(ctx context.Context, proposal *models.FixProposal, branchName string) (*models.PullRequest, error) {
	// Generate PR title and body
	title := fmt.Sprintf("[AutoFix] Fix %s in %s", string(proposal.ErrorID), proposal.ServiceName)

	body := gc.generatePRBody(proposal)

	// Create PR
	baseBranch := "main" // or "master" - could be configurable
	newPR := &github.NewPullRequest{
		Title: github.String(title),
		Head:  github.String(branchName),
		Base:  github.String(baseBranch),
		Body:  github.String(body),
	}

	pr, _, err := gc.client.PullRequests.Create(ctx, gc.owner, gc.repo, newPR)
	if err != nil {
		return nil, fmt.Errorf("failed to create PR: %w", err)
	}

	pullRequest := &models.PullRequest{
		Number:      pr.GetNumber(),
		URL:         pr.GetHTMLURL(),
		Title:       pr.GetTitle(),
		Branch:      branchName,
		ServiceName: proposal.ServiceName,
		CreatedAt:   proposal.CreatedAt,
	}

	return pullRequest, nil
}

// generatePRBody generates the PR description
func (gc *GitHubClient) generatePRBody(proposal *models.FixProposal) string {
	var body strings.Builder

	body.WriteString("## 🤖 AutoFix by TraceHub\n\n")
	body.WriteString("This PR was automatically generated to fix a detected error.\n\n")

	body.WriteString("### Error Information\n")
	body.WriteString(fmt.Sprintf("- **Service**: %s\n", proposal.ServiceName))
	body.WriteString(fmt.Sprintf("- **Error ID**: %s\n", proposal.ErrorID))
	body.WriteString(fmt.Sprintf("- **File**: %s\n\n", proposal.Fix.FilePath))

	body.WriteString("### Root Cause\n")
	body.WriteString(proposal.RootCause)
	body.WriteString("\n\n")

	body.WriteString("### Explanation\n")
	body.WriteString(proposal.Explanation)
	body.WriteString("\n\n")

	body.WriteString("### Changes\n")
	body.WriteString(proposal.Fix.Changes)
	body.WriteString("\n\n")

	if proposal.Tests != "" {
		body.WriteString("### Suggested Tests\n")
		body.WriteString("```go\n")
		body.WriteString(proposal.Tests)
		body.WriteString("\n```\n\n")
	}

	if proposal.Prevention != "" {
		body.WriteString("### Prevention Strategy\n")
		body.WriteString(proposal.Prevention)
		body.WriteString("\n\n")
	}

	body.WriteString("---\n")
	body.WriteString("⚠️ **Please review this fix carefully before merging.**\n")
	body.WriteString("While this fix was generated by AI, it should be validated by a human developer.\n")

	return body.String()
}

// ParseRepoInfo parses owner and repo from a git remote URL
func ParseRepoInfo(remoteURL string) (owner, repo string, err error) {
	// Handle different Git URL formats
	// SSH: git@github.com:owner/repo.git
	// HTTPS: https://github.com/owner/repo.git

	remoteURL = strings.TrimSpace(remoteURL)

	if strings.HasPrefix(remoteURL, "git@github.com:") {
		// SSH format
		parts := strings.TrimPrefix(remoteURL, "git@github.com:")
		parts = strings.TrimSuffix(parts, ".git")
		split := strings.Split(parts, "/")
		if len(split) != 2 {
			return "", "", fmt.Errorf("invalid SSH remote URL format")
		}
		return split[0], split[1], nil
	}

	if strings.HasPrefix(remoteURL, "https://github.com/") {
		// HTTPS format
		parts := strings.TrimPrefix(remoteURL, "https://github.com/")
		parts = strings.TrimSuffix(parts, ".git")
		split := strings.Split(parts, "/")
		if len(split) != 2 {
			return "", "", fmt.Errorf("invalid HTTPS remote URL format")
		}
		return split[0], split[1], nil
	}

	return "", "", fmt.Errorf("unsupported remote URL format: %s", remoteURL)
}
